### ISSUE TITLE
How To Use In React Native ?

### ISSUE THREAD

**Issue by loverdeveloper** [dvtng/react-loading-skeleton#10]
Hi , How i can use "react-loading-skeleton" in React Native ?

**Comment by marcoantoniocanhas** [comment]
You can use [this](https://www.npmjs.com/package/react-native-skeleton-placeholder)

**Comment by loverdeveloper** [comment]
> You can use [this](https://www.npmjs.com/package/react-native-skeleton-placeholder)

Thank you, I will check it
