### ISSUE TITLE
Circle skeleton is broken on Safari in 3.0.0

### ISSUE THREAD

**Issue by himynameissebbo** [dvtng/react-loading-skeleton#120]
**Describe the bug**
I recognized a bug in the latest release of the package occurring in Safari 15 on macOS 11.6 (saw the error in previous versions as well). The underlying animation for the skeleton is overlapping the container (see gif).

![safari](https://user-images.githubusercontent.com/18348729/138249025-52d95263-337e-490d-880f-79c98eea02f3.gif)

**To Reproduce**
1. Use latest release of `react-loading-skeleton@3.0.0`
2. Use in a React component
3. Open it with Safari 15 on macOS 11.6

**Actual Behavior**
The `background-image` is overlapping the container.

**Expected Behavior**
The animation is hidden behind the container and `overflow: hidden` is working correctly.

**Versions**
-   react-loading-skeleton version: 3.0.0
-   Browser version: Safari 15

**Additional context**
I think the problem could be fix with adding a `z-index` to the container of the animation:

```css
.react-loading-skeleton {
    ...
    z-index: 1;
}
```

**Comment by srmagura** [comment]
The `z-index` did the trick. Good idea 👍

**Comment by Jerenaux** [comment]
I am able to reproduce this issue in version 3.4.0, has the fix been undone?
