### ISSUE TITLE
Skeleton span element has 0 width

### ISSUE THREAD

**Issue by DoubleDebug** [dvtng/react-loading-skeleton#123]
Hello. I've recently tried using the react-loading-skeleton package and although it seems amazing considering its content-adapting capability, I just cannot get it to work for me. I'm sure this is not a bug, but rather something that I'm doing wrong. So please, any help is appreciated.

Here is my React component (very similar to the example code from the "Principles" section):
![1](https://user-images.githubusercontent.com/62041862/141824480-6aa1c790-ab9d-4ea5-8a08-d172dc86ac82.PNG)

As you can see, I'm using Typescript. To use the component, I did something like this:
![2](https://user-images.githubusercontent.com/62041862/141825036-04b6620c-20e8-4173-9d42-237dc5188462.PNG)

However, when I load the page in the browser, I get this:
![3](https://user-images.githubusercontent.com/62041862/141825151-0176ebee-1044-4839-b824-c20efaa3ad22.png)

The span element, which is supposed to represent the Skeleton is invisible and ALWAYS has 0 width.
How is the width of the Skeleton element determined? Shouldn't it default to the width of 100%?

What am I doing wrong?
Thank you in advance.

**Comment by srmagura** [comment]
Hey @DoubleDebug, if I had to guess, your `Temp` component is in a flex container. My comment on this issue may be helpful to you: #122.

If that doesn't help, could you create a CodeSandbox? That would help me figure out what is going wrong.

**Comment by DoubleDebug** [comment]
Thanks for the quick reply, @srmagura.

I wasn't aware of the flex container issue you mentioned, however, that's not what's causing the problem for me.
The parent element of my Temp component had the `display` property set to `block`, as well as all of his parent elements.

Here's a [CodeSandbox](https://codesandbox.io/s/l8rhf) that might help.

**Comment by srmagura** [comment]
Ah, you are missing the required CSS import. Add this to the top of your file and it will work:

```ts
import 'react-loading-skeleton/dist/skeleton.css'
```

**Comment by DoubleDebug** [comment]
Thanks so much, @srmagura. I knew it was something so trivial.
