### ISSUE TITLE
css line import issue on live

### ISSUE THREAD

**Issue by Sirbuland** [dvtng/react-loading-skeleton#131]
**Describe the bug**
Its working fine on local but not on staging (live). Actually its not visible because css is not importing correctly. As i removed [import 'react-loading-skeleton/dist/skeleton.css'] that line on local and got live results (live invisible behavior). I am sure i added css import line in file and pushed. 

**To Reproduce**
Push code on any live server its not visible there

**Actual Behavior**
What actually happened.

**Expected Behavior**

**Versions**
3.0.1
-   react-loading-skeleton version:
-   Browser version:

**Additional context**

**Comment by srmagura** [comment]
Hey @Sirbuland, I use `react-loading-skeleton` in a production application and the CSS import does work in production. Are you able to provide a minimal reproduction of the issue you are experiencing?

Does the import work if you run a production build of your application on localhost?
