### ISSUE TITLE
Spacing multiple lines

### ISSUE THREAD

**Issue by JBaczuk** [dvtng/react-loading-skeleton#132]
I'm wondering if there is an acceptable way to allow custom spacing rather than a `<br>` between skeleton lines. Could this be a prop that changes a CSS `gap` value for a column flexbox?

https://github.com/dvtng/react-loading-skeleton/blob/1cb22a1a7a857ef9aff03a1521204180ffb5e91a/src/Skeleton.tsx#L114

**Comment by srmagura** [comment]
Hmm, what is the exact problem you are encountering? Can you fix it by setting the `line-height`?

**Comment by JBaczuk** [comment]
I've got a list of items in a column flex that have a gap of 0.5rem, and line-height of 24px.

![image](https://user-images.githubusercontent.com/8162417/151005660-af7f785b-1be3-4828-a84d-3ed115d9a75a.png)

I'd like the loading skeleton to look like this (current code: `<Skeleton count={5} height={24} style={{ marginBottom: 4 }} />`):

![image](https://user-images.githubusercontent.com/8162417/151005920-34873431-2a5b-42ff-8c03-a429c84b0b3c.png)

But without custom styling, it looks like this `<Skeleton count={5} height={24} />`:

![image](https://user-images.githubusercontent.com/8162417/151006474-63a3b9af-dbb4-4252-ba1e-f87edbd70c1e.png)

**Comment by srmagura** [comment]
Thanks, that helps. The philosophy when using react-loading-skeleton is to have your skeleton JSX match the "real" JSX as closely as possible.

Your "real" JSX (when the search results have loaded) is something like this:

```tsx
return <div className="flex flex-col ...">
    <div className="search-result">Value 1</div>
    <div className="search-result">Value 2</div>
    <div className="search-result">Value 3</div>
</div>
```

So I would make the Skeleton JSX like this:

```tsx
return <div className="flex flex-col ...">
    <div className="search-result"><Skeleton /></div>
    <div className="search-result"><Skeleton /></div>
    <div className="search-result"><Skeleton /></div>
</div>
```

That way, the skeleton screen will use the same line-height, gap, .etc as the screen with the real data displayed. Let me know if that makes sense.

**Comment by JBaczuk** [comment]
It makes sense, so if you had an array of data returned from an API call, would you suggest something like this?

```
  return (
    <div className="flex flex-col ...">
      {results.length > 0
        ? results.map((item) => <div className="search-result">{item}</div>)
        : [...Array(5)].map(() => (
            <div className="search-result">
              <Skeleton />
            </div>
          ))}
    </div>
  )
```

**Comment by srmagura** [comment]
That's the right idea. I would define a component like this:

```tsx
function SearchResult({ item }) {
    return <div className="search-result">{item ? <>Real data goes here</> : <Skeleton /></div>
}
```

Alternatively, you can use the `wrapper` prop which works well with the `count` prop. There is an example of this in our Storybook [here](https://github.com/dvtng/react-loading-skeleton/blob/master/src/__stories__/Skeleton.stories.tsx#L41).

**Comment by srmagura** [comment]
Closing as I think your question has been answered. Let me know if there is anything else you want help with.
