### ISSUE TITLE
Passing decimals to count

### ISSUE THREAD

**Issue by AdaptingAFM** [dvtng/react-loading-skeleton#136]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
If count is equal to 2.5, return three animated spans: 2 with 100% the width, and one with 50% the width.

**Describe alternatives you've considered**

**Additional context**

**Comment by srmagura** [comment]
Hey @AdaptingAFM. On one hand, this does sound like a nice convenience. On the other hand, I can't see many people using this feature.

I'm going to leave this open for a while — if it gets a nontrivial number of +1's, I'll consider implementing it. In the meantime, you could write your own component that accepts non-integer `count` and renders the appropriate `<Skeleton />`'s.

**Comment by srmagura** [comment]
This is scheduled for implementation 😀
