### ISSUE TITLE
Adding margin props?

### ISSUE THREAD

**Issue by simpson** [dvtng/react-loading-skeleton#14]
Any thoughts on adding margin props? It would be helpful for fixing issues like this

<img width="269" alt="screenshot 2018-09-18 09 13 11" src="https://user-images.githubusercontent.com/1605737/45689924-37402400-bb23-11e8-9a9c-c5e68f50e273.png">
<img width="261" alt="screenshot 2018-09-18 09 13 54" src="https://user-images.githubusercontent.com/1605737/45689925-37402400-bb23-11e8-941a-08e4cd8e950a.png">

**Comment by dons20** [comment]
Have you tried tweaking the css of the container? It should adapt to your css without needing to modify the component directly. Maybe you could try a flexbox for example.

**Comment by ijakparov** [comment]
> Have you tried tweaking the css of the container? It should adapt to your css without needing to modify the component directly. Maybe you could try a flexbox for example.

I don't understand how to add margins too. May be you'll add some other css props?

**Comment by giolvani** [comment]
According to storybook samples, you can use a wrapper for additional styles. I did it with a styled component, for example.

```
const Box = styled.span`
  display: inline-block;
  margin-bottom: 4px;
  width: 100%;
`;
```
so in your component you can call like that:
`<Skeleton wrapper={Box} />`


Hope I can help.

**Comment by nickforbizz** [comment]
<Skeleton width="100%" height="2rem"  style={{margin:"1rem"}}/>

**Comment by srmagura** [comment]
Seems like this issue is solved, please reopen if that's not the case.
