### ISSUE TITLE
Skeleton not showing in React v.18

### ISSUE THREAD

**Issue by nikitapryymak** [dvtng/react-loading-skeleton#140]
**Describe the bug**
When trying to use the Skeleton component in React v.18, nothing displays. The span.react-loading-skeleton is in the DOM, but doesn't display

**To Reproduce**
Create a React app using v.18 and try to use a Skeleton

**Actual Behavior**
Skelton doesn't display

**Expected Behavior**
A skeleton should display

**Versions**

-   react-loading-skeleton version: 3.0.1
-   Browser version: Chrome 100.0.4896.88

**Comment by trumbitta** [comment]
Hey @nikitapryymak 👋

Did you close this because you found a solution? I'm evaluating if I can upgrade to R18 myself and any insight would be really helpful 🙏

**Comment by nikitapryymak** [comment]
Hi @trumbitta ! No I realized that I wasn't importing the necessary CSS file that u need for v.3 🤦🏼‍♂️

**Comment by TatianaMatumoto** [comment]
I was with the same problem, and resolved the same way. Maybe put explicit in the READ.ME about the v.3 changes instead of a link?
