### ISSUE TITLE
Skeleton in not displayed properly

### ISSUE THREAD

**Issue by rgdzv** [dvtng/react-loading-skeleton#143]
**Describe the bug**
Skeleton in not displayed.
Details: parent span of the skeleton is displayed with proper width but child span has 0 width.

**To Reproduce**
Skeleton is not displayed on the local server

**Actual Behavior**
Parent span of the skeleton is displayed with proper width but child span has 0 width.

**Expected Behavior**
Skeleton needs to be displayed with proper width.

**Versions**

-   react-loading-skeleton version: 3.1.0
-   React JS version: 18.1.0
-   Opera version: 88.0.4412.74
-   Webpack version: 5.73.0

**Additional context**

Trying to use skeleton, but it's not displayed.
Tried already:
- reinstallation
- `import 'react-loading-skeleton/dist/skeleton.css'` string is present (doesn't matter where I put it: top or bottom of imports)
- not the `width` prop neither `containerClassName` prop of `Skeleton` component with CSS rule `flex-grow-1` helps

Code for Skeleton component:
![1](https://user-images.githubusercontent.com/60195076/177955712-16da0d8a-6c7b-4a00-9b08-08b6a6569bce.png)

Webpack modules rule for css:
![2](https://user-images.githubusercontent.com/60195076/177955860-5fd083ee-b24b-4e04-aa73-17ef5c383181.png)

Browser look:
![1](https://user-images.githubusercontent.com/60195076/177956801-95285901-8d99-43a2-8381-5a48b39b8d67.jpg)
![2](https://user-images.githubusercontent.com/60195076/177956823-d44469ea-8e82-4526-800e-eb5e85cd3212.jpg)

**Comment by srmagura** [comment]
Please provide a runnable example that shows the problem. The styles from your CSS module (`styles.skeleton`) are likely relevant here.

**Comment by rgdzv** [comment]
`styles.skeleton` consist of:
```
    width: 100%;
    height: 100%;
    display: flex;
    flex-direction: column;
```

**Comment by srmagura** [comment]
Have you confirmed that our `skeleton.css` is being imported into the webpage? You can check this by looking at the styles on the `.react-loading-skeleton` element — you should see some styles coming from our CSS file.

If you are still having issues, please create a GitHub repo that shows the problem and I will be happy to look at it.

**Comment by rgdzv** [comment]
@srmagura,  yes, I can see, that child span has `react-loading-skeleton` class and styles are used, but span has 0 `width`

I created a repo here: https://github.com/rgdzv/react-pizza

Just clone and then:
- npm install,
- npm start

**Comment by srmagura** [comment]
`skeleton.css` was not being loaded due to an issue with your Webpack config. Check out my PR to your repo: https://github.com/rgdzv/react-pizza/pull/1

**Comment by rgdzv** [comment]
@srmagura , tnx, it helped. Now, I need to understand how to fix the situation if I want to use names for my modules)
