### ISSUE TITLE
Doesn't work with SSR

### ISSUE THREAD

**Issue by beautyfree** [dvtng/react-loading-skeleton#15]
```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/some_path/node_modules/react-loading-skeleton/dist/bundle.js:1:240)
```

**Comment by tchalvak** [comment]
@beautyfree we’re you able to solve this or work around it somehow?

**Comment by Bryze** [comment]
Any updates on this?

**Comment by tchalvak** [comment]
@Bryze won’t even build in standard react build to static site for me, so I ended up ripping to skeletons back out since I needed to deploy a react static site.
