### ISSUE TITLE
Adding React "use client" directives for Next 13

### ISSUE THREAD

**Issue by cravend** [dvtng/react-loading-skeleton#161]
**Describe the bug**
Right now, context is being used without the new `"use client"` directive. This makes sense, because the directive is so new. However, when using `react-loading-skeleton` with the Next 13 app directory, it causes an error — `useContext` is a client-only API.

**To Reproduce**
- create next 13 app dir
- install `react-loading-skeleton`
- try to use `<Skeleton />` in a server or shared component.

**Actual Behavior**
An error is thrown:

```
Server Error
TypeError: createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

**Expected Behavior**
No error is thrown.

**Versions**

-   react-loading-skeleton version: 3.1.0
-   Browser version: Safari 16.2

**Additional context**
- https://nextjs.org/docs/messages/context-in-server-component
- https://beta.nextjs.org/docs/rendering/server-and-client-components#third-party-packages
- https://github.com/reactjs/rfcs/blob/main/text/0227-server-module-conventions.md

**Comment by cravend** [comment]
I believe that the fix is as simple as adding the use client directive — I can do it, just wanted to create an issue first for documentation.

**Comment by cravend** [comment]
Actually, looks like this might be blocked by rollup: https://github.com/rollup/rollup/issues/4699

There's a few suggested workarounds...

**Comment by srmagura** [comment]
I was waiting for someone to post about this 😆. Based on my limited understanding of React Server Components, I think the solution is just to add the `'use client'` directive. 

It looks like we could use the Rollup `banner` option to insert the directive as has been suggested in the issue you linked. React Loading Skeleton has no dependencies, so there shouldn't be any harm in marking the entire bundle as `'use client'`.
