### ISSUE TITLE
Support for reduced motion

### ISSUE THREAD

**Issue by IDrumsey** [dvtng/react-loading-skeleton#164]
**Is your feature request related to a problem? Please describe.**
It would be good to support reduced motion for accessibility concerns and reducing the load on users of the library to implement this themselves for the library components.

**Describe the solution you'd like**
When reduced motion is preferred, don't show the shimmer effect.

**Describe alternatives you've considered**
Somehow removing the shimmer effect from my own code with classes or something.

**Additional context**
I haven't done a whole lot of research into the accessibility / health concerns surrounding reduced motion, but I think it applies here.

**Comment by srmagura** [comment]
Great idea. I think this should be pretty easy to implement. I'll get back to you on this soon.

**Comment by srmagura** [comment]
Thanks @RoseMagura for agreeing to help with this. Here's a good resource on `prefers-reduced-motion`: https://web.dev/prefers-reduced-motion/. I _think_ you can implement support for it in react-loading-skeleton just by editing the CSS file (no JavaScript changes).
