### ISSUE TITLE
Mac: setting <Reduce Motion>

### ISSUE THREAD

**Issue by EnricoMariaFabbri** [dvtng/react-loading-skeleton#174]
If mac has enabled the setting "Reduce Motion" the animation isn't showing

**Comment by srmagura** [comment]
Hi Enrico, this is an intentional feature that we added recently.

What do you think the ideal behavior would be when the "prefers reduced motion" setting is enabled? Maybe you want the animation to play but at a slower speed.

**Comment by EnricoMariaFabbri** [comment]
yes it this could be a nice feature

**Comment by RoseMagura** [comment]
After referencing [this article](https://www.smashingmagazine.com/2020/09/design-reduced-motion-sensitivities/), we have disabled the translation animation if a user has the `prefers-reduced-motion` setting enabled. This will help users with motion sensitivity to use react-loading-skeleton safely.

If there is enough interest, we can add an option to allow the animation even if `prefers-reduced-motion` is enabled.

**Comment by srmagura** [comment]
Closing since the currently-implemented behavior seems correct. (no animation when the user prefers reduced motion)
