### ISSUE TITLE
Fill wrapping container

### ISSUE THREAD

**Issue by SirVizzy** [dvtng/react-loading-skeleton#175]
I'm trying to make it so the skeleton fills its parent container. However doing this the skeleton is always pushed down.

![image](https://user-images.githubusercontent.com/54225154/227378963-070c160b-f526-4b86-89c3-39c1d5d60f4b.png)

**Code**
```
<div style={{ padding: 1, height: 100, width: 100, backgroundColor: 'red' }}>
    <Skeleton
        height="100%"
        width="100%"
        inline
    />
</div>
```

Is there any convenient solution for this?

**Comment by srmagura** [comment]
Hello, have you tried adding `lineHeight: 1` to the outer `<div>`?

**Comment by SirVizzy** [comment]
> Hello, have you tried adding `lineHeight: 1` to the outer `<div>`?

Yes, this does work. Having `lineHeight: 1` on the parent and `height: 100%`, `width: 100%`, `display: block` on the parent container. Wouldn't it be good if we had a `fill` property that would apply these values? I'm using Tailwind and I prefer not having to define custom classes.

**Comment by srmagura** [comment]
Another option which works well with Tailwind is to create a React component to encapsulate those styles.
