### ISSUE TITLE
Edge Support 

### ISSUE THREAD

**Issue by KLD** [dvtng/react-loading-skeleton#18]
Does not animate on Edge 

I tried Chrome and Firefox, and iOS Safari. Works.

**Comment by joeyslack** [comment]
FYI, it's because Edge doesn't support `calc` inside the transform. Would be super easy to fork this project, and use translateX instead of calc.

**Comment by chrisvalle35** [comment]
@joeyslack I gave your suggestion a quick try and it didn't seem to work for me.  I changed `background-position: calc(200px + 100%)` to `background-position-x: translateX(200px) translateX(100%)` and it didn't seem to work.  

Do you mind posting an example of what you were mentioning?

**Comment by srmagura** [comment]
No longer an issue since Edge is now Chromium-based. Can be closed.
