### ISSUE TITLE
Version 3.3.0 contains breaking changes compared to 3.2.0

### ISSUE THREAD

**Issue by holblin** [dvtng/react-loading-skeleton#189]
**Describe the bug**
Where version 3.3.0 is used, the unit-test (jest) in my application crashes while it wasn't the case with 3.2.0

```
    Details:

    project-path/node_modules/react-loading-skeleton/dist/index.js:2
    import React from 'react';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

**To Reproduce**
Run unit-test with Jest, React, Typescript (4.7.4)

**Actual Behavior**
Jest tests are crashing.

**Expected Behavior**
The upgrade shouldn't bring breaking changes on minor changes. See https://semver.org/

**Versions**

- react-loading-skeleton version: 3.3.0
- Browser version: Not relevant.

**Comment by srmagura** [comment]
Thank you for reporting! I have fixed the mistake in #191. Until 3.3.1 is deployed, please continue to use 3.2.0.

I did test the 3.3.0 release in Jest, and it worked. I wonder what's different about your setup than what I tested with...
