### ISSUE TITLE
Not working with nextjs loading.tsx

### ISSUE THREAD

**Issue by learnatwhitecoal** [dvtng/react-loading-skeleton#192]
Here is my code :
I have app directory and this has following files:
app /
    - layout.tsx
    - page.tsx
    - loading.tsx
   

```import Skeleton from "react-loading-skeleton";
import 'react-loading-skeleton/dist/skeleton.css'
const loading = () => {
  return (
    <>
      <div className="home-page px-4">
        <div className="sidebar h-[20rem] text-white text-lg bg-slate-400 flex justify-center items-center">
          <Skeleton/>
        </div>
        <div className="our-products mt-3">
          <h2 className="font-medium text-lg">Our Products</h2>
          <div className="product-wrappers flex gap-2 gap-y-4 flex-wrap"></div>
        </div>
      </div>
    </>
  );
};

export default loading;

```

But skeleton is not showing on loading.tsx but showing on page.tsx

**Comment by srmagura** [comment]
I wonder if this issue is caused by something fancy the new Next.js app router is doing. Can you submit a runnable project that reproduces the issue so I can investigate?

**Comment by SanderCokart** [comment]
There is a funny thing going on, despite the source code declaring a `'use client';` When doing this in lets say a providers component wrapping the app:

```ts
import type {ReactNode} from 'react';
import {SkeletonTheme} from 'react-loading-skeleton';

export default function Providers({ children }: { children: ReactNode }) {
    return (
        <SkeletonTheme baseColor="var(--loading-base)" highlightColor="var(--loading-highlight)">
            {children}
        </SkeletonTheme>
    );
}
```
It only provides the theme to the server rendered Skeletons.

If we add a `'use client';` at the top of the page it only provides the context to client components instead. Super funny.


https://github.com/dvtng/react-loading-skeleton/assets/45256817/d2a55a93-0e55-4e36-966a-5806377998fc

As you can see it switches around.

**Comment by srmagura** [comment]
Hey @SanderCokart, it seems like there may be a real issue here. Are you able to submit a minimal repro that I can run, so that I can investigate the issue?

**Comment by SanderCokart** [comment]
@srmagura here is a repo showing how you need a client and server provider separately: https://github.com/SanderCokart/next-13-playground

**Comment by srmagura** [comment]
@SanderCokart Can you create a new issue and include a more _minimal_ code example? Meaning, please remove all code that is not necessary to reproduce the issue. Please also describe the expected behavior and the actual behavior.

If you can do that, it will help me figure out the issue. Thank you.
