### ISSUE TITLE
i have npm v18 and skeleton loading animation is not working with me please any help

### ISSUE THREAD

**Issue by SaidosHits** [dvtng/react-loading-skeleton#198]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Actual Behavior**
What actually happened.

**Expected Behavior**

**Versions**

- react-loading-skeleton version:
- Browser version:

**Additional context**

**Comment by mrisher** [comment]
Similar: I am seeing white bars in the correct color but no animation is happening.  The CSS properties seem correct and the CSS file is loading... 
<img width="568" alt="image" src="https://github.com/dvtng/react-loading-skeleton/assets/218038/041fbe48-b385-4e68-bdb1-365bcf36e46a">

**Comment by mrisher** [comment]
The problem for me was, the colors #ebebeb and #f5f5f5 are too close to see the animation. Changing `--base-color: #919191` made the effect noticeable and works for me
<img width="452" alt="image" src="https://github.com/dvtng/react-loading-skeleton/assets/218038/c45eb173-4040-4db2-a982-de4edcb123b9">

**Comment by srmagura** [comment]
Thanks @mrisher.

Closing the issue since the original post does not have any repro steps / .etc.

**Comment by mrisher** [comment]
agreed. Thank you!
