### ISSUE TITLE
FEAT REQ - highlight width

### ISSUE THREAD

**Issue by nicitaacom** [dvtng/react-loading-skeleton#213]
![2023-12-06_14-51](https://github.com/dvtng/react-loading-skeleton/assets/39565703/3ec69481-d4cb-4a4c-917c-82b99b8344ff)

**Describe the solution you'd like**
prop that I can add here for highlight width
![image](https://github.com/dvtng/react-loading-skeleton/assets/39565703/17ac2ab2-0c04-40a9-9dbb-251fad9fbe51)

**Describe alternatives you've considered**
its crutch
Create 4 skeletons with different durations like `duration={2}` `duration={4}` etc

**Comment by srmagura** [comment]
I implemented this and have sent an email to dvtng asking for review.

**Comment by nicitaacom** [comment]
> I implemented this and have sent an email to dvtng asking for review.

Thank you!
