### ISSUE TITLE
v3.4.0 available on NPM but not in repo. Legit release?

### ISSUE THREAD

**Issue by areriklq** [dvtng/react-loading-skeleton#219]
**Describe the bug**
I see v3.4.0 on NPM but there is no Github releae or Git tag corresponding to this version. Is it a legit release?

https://www.npmjs.com/package/react-loading-skeleton/v/3.4.0

**To Reproduce**
Visit NPM and look at latest release.
Compare with this repo.

**Actual Behavior**
This repo has no references to a v3.4.0 release

**Expected Behavior**
This repo should have references to a v3.4.0 release

**Versions**

- react-loading-skeleton version:
- Browser version:

**Additional context**

**Comment by srmagura** [comment]
It is a legitimate release. I just forgot to create the release in GitHub. I have done so now.

**Comment by areriklq** [comment]
Thank you!
(Given the supply-chain-attacks happening the diff between NPM and the repo got me worried)
