### ISSUE TITLE
Radius props?

### ISSUE THREAD

**Issue by Shravan89131** [dvtng/react-loading-skeleton#22]
Do we have any radius prop for this? I want to set the Skeleton for a button with a curved edges

**Comment by ianjanicki** [comment]
If you're stuck: Solved this by wrapping with a div with css rule making all `span` children to get my desired radius . In JSS it would look like:
```
'& span': {
   borderRadius: 10
}
```

Ideally the solution here is for the theme component can consume any CSS property.

**Comment by srmagura** [comment]
Closing in favor of #32.
