### ISSUE TITLE
baseColor not working

### ISSUE THREAD

**Issue by websnooze** [dvtng/react-loading-skeleton#220]
**Describe the bug**
I'm using TailwindCSS on react project, highlightColor is working but when I put baseColor prop, it's not working

**To Reproduce**
Using tailwind css

**Actual Behavior**
Nothing happen, both base and highlight colors not working

**Expected Behavior**
Working..

**Versions**

- react-loading-skeleton version: ^3.4.0
- Browser version: Chrome 121.0.6167.185 (Build officiel) (64 bits)

**Comment by srmagura** [comment]
Please submit a runnable example that shows the problem (e.g. CodeSandbox). It is probably not relevant that you are using Tailwind.
