### ISSUE TITLE
Make the width dynamically responsive

### ISSUE THREAD

**Issue by Ibeenoch** [dvtng/react-loading-skeleton#231]
Is there a way to make the width responsive? 
I tried using width:"100%" But it ain't working

I want the width to be dynamic across different screen sizes is there a way to achieve it, with normal CSS or tailwindCSS?

**Comment by maliuta-oleksandr** [comment]
Up

**Comment by srmagura** [comment]
JSX: `<Skeleton containerClassName="my-skeleton" />`

CSS: 
```css
.my-skeleton {
  width: 100%;
}
```

https://stackblitz.com/edit/vitejs-vite-csc3ei?file=src%2Findex.css
