### ISSUE TITLE
 Circle skeleton is broken on Safari in 3.4.0 

### ISSUE THREAD

**Issue by Jerenaux** [dvtng/react-loading-skeleton#232]
This is basically the exact same issue as in this issue: [Circle skeleton is broken on Safari in 3.0.0 #120 ](https://github.com/dvtng/react-loading-skeleton/issues/120). It seems it was fixed but I'm able to reproduce with:

- Safari 15.5
- `react-loading-skeleton@3.4.0`
- MacOS 12.4

**Comment by srmagura** [comment]
Looks fine to me Safari 17.6 on iPad (iOS 17.6.1).

Are you able to reproduce in our Storybook? Clone the repo, run `yarn install` then `yarn storybook`. The story is Skeleton > Circle.

If you can reproduce in Storybook, it must be related to you using a somewhat old version of Safari.

![PXL_20240921_160619967](https://github.com/user-attachments/assets/a773d27b-c2e8-4965-882f-5a5996817498)

**Comment by srmagura** [comment]
This is probably the change that caused it: https://github.com/dvtng/react-loading-skeleton/releases/tag/v3.4.0

I don't really want to revert that change if it works in the latest Safari.

**Comment by Jerenaux** [comment]
Yes I'm able to reproduce in Storybook! If it's a quirk on my side then it's fine, I assume then that most of my users won't experience it, thanks for the feedback!
