### ISSUE TITLE
The animation does not work.

### ISSUE THREAD

**Issue by marekrozmus** [dvtng/react-loading-skeleton#237]
**Describe the bug**
The animation does not work. I have tried in my project and on the sandbox from readme.

**Actual Behavior**
Only color rectangles are shown.

**Expected Behavior**
The animation should be played.

**Versions**

- react-loading-skeleton version: 3.5.0
- Browser version:

**Additional context**
Or am I doing something wrong :) ?

**Comment by srmagura** [comment]
Check if you have the "Prefers reduced motion" setting enabled in your browser settings. If that setting is true, react-loading-skeleton does not animate.

**Comment by marekrozmus** [comment]
@srmagura You are right :/ I got animations effects off in Window settings. Didn't realize that there is a [setting in CSS for this](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#user_preferences). Thank you :) at least now I understand the reason.
