### ISSUE TITLE
span englobing tag is causing DOM validation issues

### ISSUE THREAD

**Issue by HHK1** [dvtng/react-loading-skeleton#28]
I'm using the Skeleton component inside a table to show that the rows are loading.

I'm getting DOM validation warnings, because the Skeleton component contains a `<span>` at the root. Specifically, the` <span>` cannot appear as a child of a `<tbody>`. I've tried using the wrapper props, to include the skeletons inside a `<tr>`, but the englobing span is still causing issues. 

Could this be replaced with something else ? A fragment, or a div ? Is it absolutely necessary to use a span ?

**Comment by VGamezz19** [comment]
+1

**Comment by CKGrafico** [comment]
You can use wrapper https://github.com/dvtng/react-loading-skeleton/blob/master/stories/Skeleton.story.js#L25

**Comment by srmagura** [comment]
Rendering a `Skeleton` as a direct child of a `tbody` should be avoided. You need to put the `Skeleton` inside a table cell, for example:

```tsx
<table>
    <tbody>
        <tr>
            <td><Skeleton /></td>
            <td><Skeleton /></td>
            <td><Skeleton /></td>
        </tr>
    </tbody>
</table>
```
