### ISSUE TITLE
npm start error on windows

### ISSUE THREAD

**Issue by msman** [dvtng/react-loading-skeleton#3]
Hi,
I really appreciate you for this work. But I wanted to benefit from the examples, but I get error when 'npm start' on windows 10.  Attached is the log file.

[npm-debug.log](https://github.com/dvtng/react-loading-skeleton/files/1433218/npm-debug.log)

**Comment by dvtng** [comment]
Hi @msman, there's no start script for the project, but you can run `npm run storybook` instead. I should add a start script though, so thanks for bringing it up!

**Comment by dvtng** [comment]
I've added a start script now, so you should be able to just run `npm start`.
