### ISSUE TITLE
Being able to fill entire container

### ISSUE THREAD

**Issue by michaelgaigg** [dvtng/react-loading-skeleton#31]
Need to be able to create a block that fills the entire width or even height of a given container, i.e. width=100%

**Comment by anied** [comment]
I believe that this is possible by passing the `height` prop the string `"100%"`; _however_, this doesn't work with a themed skeleton; I'm looking in to whether it might be worth opening a PR that would allow for the theme to be passed styles...

**Comment by Mako-L** [comment]
> I believe that this is possible by passing the `height` prop the string `"100%"`; _however_, this doesn't work with a themed skeleton; I'm looking in to whether it might be worth opening a PR that would allow for the theme to be passed styles...
> 
> One workaround I found for the full height theme-wrapped skeleton was to make the containing parent `display: flex;` when the skeleton is being shown.

A fix would be nice for this. I'm trying to do the same thing.

**Comment by srmagura** [comment]
This is all working in the upcoming version 3. 

In a `display: block` container, this works: `<Skeleton height="100%" />`. Width is 100% by default.

In a flex or grid container, you'll also have to use `containerClassName`: 

```tsx
<Skeleton height="100%" containerClassName="max-container" />
```
```css
.max-container {
    width: 100%;
    height: 100%;
}
```

_Note:_ The word "container" is a bit overloaded here. There is the container that you render, and then there is the `<span>` container that react-loading-skeleton renders around the skeletons. `containerClassName` applies to this `<span>`.
