### ISSUE TITLE
SkeletonTheme can't be changed at runtime

### ISSUE THREAD

**Issue by leoxs22** [dvtng/react-loading-skeleton#36]
I have two themes in my site that can be changed in any moment. I'd like to change SkeletonTheme with it.

I've tried using ternary operators in the colors, and I even made a wrapper component:

```
import React from 'react';
import {SkeletonTheme} from "react-loading-skeleton";

const ThemeAwareSkeletonTheme = ({theme, children}) => {
    if (theme === "white") {
        return (<SkeletonTheme color={"#eee"} highlightColor={"#f5f5f5"}>{children}</SkeletonTheme>)
    } else {
        return (<SkeletonTheme color={"#245b89"} highlightColor={"#152e4d"}>{children}</SkeletonTheme>)
    }
};

export default ThemeAwareSkeletonTheme;
```

But it doesn't work, if the first loaded theme is white, it can't be changed to the other one, it just keeps the same colors.

I can't find in the code what is causing it, can you help me to find it?

Thanks!

Regards

**Comment by dvtng** [comment]
Fixed in v1.3.0
