### ISSUE TITLE
Args is undefined after attempting to import

### ISSUE THREAD

**Issue by rpanczer** [dvtng/react-loading-skeleton#43]
<img width="410" alt="image" src="https://user-images.githubusercontent.com/15878614/73379179-1dd7ec00-42c2-11ea-92fb-20a8916d8754.png">

I did an npm install of the repo, restarted my react app and imported the Skeleton component. I received the error `args is undefined`.

**Comment by srmagura** [comment]
If you're still having this issue, please provide a code sample and I will look into it. Thanks.
