### ISSUE TITLE
Add live demo

### ISSUE THREAD

**Issue by LaksCastro** [dvtng/react-loading-skeleton#44]
This package is awesome, but not have a live demo page :|

Today, any React Package need a demo page, use some React Lib, like React Live

Or deploy a simple HTML and Css page, like there: https://lakscastro.github.io/menu-hamburger

The most important is show your lib working

Thank you, and I hope it takes into account the suggestion :)

**Comment by JasonXiaoSpace** [comment]
so where is the demo

**Comment by srmagura** [comment]
This is a work in progress at https://github.com/srmagura/react-loading-skeleton-site...

**Comment by srmagura** [comment]
The website has been backlogged for now, but you can check out the new [CodeSandbox](https://codesandbox.io/s/react-loading-skeleton-3xwil?file=/src/App.tsx) for a live demo 🙂
