### ISSUE TITLE
Export SkeletonProps and SkeletonThemeProps interfaces

### ISSUE THREAD

**Issue by daviddelusenet** [dvtng/react-loading-skeleton#45]
My team is using this library in a TypeScript project. We've build a wrapper component around a `Skeleton` component because our wrapper components supports some additional props.

However, we also support all of the props mentioned in the `SkeletonProps` interface so we want to extend this interface. This isn't possible because the `SkeletonProps` and SkeletonThemeProps` aren't exported.

**Comment by dvtng** [comment]
This is available as of v2.1.1.
