### ISSUE TITLE
Change SkeletonTheme element to span

### ISSUE THREAD

**Issue by daviddelusenet** [dvtng/react-loading-skeleton#46]
The `SkeletonTheme` element is now a `div`. However, if you want to render this component inside of a `p` React will start complaining.

**Comment by baleeds** [comment]
Also, not being able to style the `SkeletonTheme` is breaking our project, since we need it to be full height.  Is there a way to not have the `SkeletonTheme` pollute the DOM?

**Comment by audiolion** [comment]
might be nice for the element rendered to be configurable, div, p, span, let the user of the library decide, with the default being <div /> so it doesn't break existing users UI

**Comment by baleeds** [comment]
Yeah that's a really good point.  I'm not exactly sure what case there is where people want the div to exist.  It can't be styled or anything, it just sits there.  But I could see potential breaking happening due to the change.

**Comment by srmagura** [comment]
Closing in favor of #101.
