### ISSUE TITLE
Skeleton Mask Function (New Feature)

### ISSUE THREAD

**Issue by srianbury** [dvtng/react-loading-skeleton#51]
What are your thoughts on adding a function like the following (this is a quick example) as part of the package?  My idea is to show the data when it's available and `<Skeleton />` otherwise.
```
function skeletonMask(data, options = {}){
  const {
    skeleton = <Skeleton />,
    view = data
  } = options;
  return !data ? skeleton : view;
}
```
Example Usage:
```
const View = ({ id, title, completed }) => (
  <div>
    <div>{skeletonMask(completed)}</div>
    <div>{skeletonMask(id, { skeleton: <Skeleton height={50} />})}</div>
    <div>{skeletonMask(title, { view: `Title: ${title}`})}</div>
  </div>
);
```

**Comment by dvtng** [comment]
This seems like too specific of a pattern to be included the library, but would be perfect as a utility function in userland!

**Comment by srianbury** [comment]
I agree looking at this now. Thanks for the feedback!
