### ISSUE TITLE
Need to Support Style Props and ClassName Props

### ISSUE THREAD

**Issue by totalard** [dvtng/react-loading-skeleton#52]
Need to Support Style Props and ClassName Props

Nothing to Tell more. currently skeleton not supports style props and classname props

**Comment by asherccohen** [comment]
I agree on this.
Styling can be easily added with styled-components or by exposing css.

Use case is being able to do something like this:

const StyledSkeleton = styled(Skeleton)`
  border-radius: 0;
`;

**Comment by mrtheyann** [comment]
Agree on this.
There is an [approved pull request](https://github.com/dvtng/react-loading-skeleton/pull/53) already, but it has not been merged yet, I wonder why.

**Comment by matteo95g** [comment]
Hi, same as above, it would be nice to have custom styles added with `className` prop 😄

**Comment by dvtng** [comment]
Thanks for the patience everyone. Both style and className props are available as of v2.1.1.
