### ISSUE TITLE
Really Need Support For Typescript Integration

### ISSUE THREAD

**Issue by anhkysu** [dvtng/react-loading-skeleton#54]
Really Need Support For Typescript Integration!
I'm going to make a scalable ReactJS App using Typescript, and I'm so dissapointed because this beautiful library has not supported typescript yet. Please add support to this to make your library more awesome.
After some research at the NPM market, there is no skeleton library supportting typescript. So, chances are you will make a difference.
Really appreciate it if you could help!

**Comment by dvtng** [comment]
Thanks for submitting this issue. Typescript definitions should be available as of v2.1.1.
