### ISSUE TITLE
Not working inside iframe

### ISSUE THREAD

**Issue by VictorBaudot** [dvtng/react-loading-skeleton#56]
I'm using `react-frame-component` to put part of my app inside an iframe and none of the css of the Skeletons inserted inside the iframe are generated. I don't get why

**Comment by srmagura** [comment]
I got `Skeleton` version 3 to work inside react-frame-component. Here's the React code:

```tsx
<Frame head={<link href="skeleton.css" rel="stylesheet" />}>
    <Skeleton count={5} />
</Frame>
```

For this to work, you need to copy `skeleton.css` to your `public` folder (Create React App), `wwwroot` (ASP.NET Core), or similar.

[Full working example](https://github.com/srmagura/react-loading-skeleton-test-projects/tree/main/react-frame-component)
