### ISSUE TITLE
Does not display if width in % and child of Flex or Grid

### ISSUE THREAD

**Issue by johnruane** [dvtng/react-loading-skeleton#61]
I want to use percent widths in a responsive layout, but if the Skeleton component is within a Flex or Grid parent then you must supply a px width. Is there any plan to add a classname to the default 'span' wrapper? This would at least allow me to add a custom style object in this situation.

**Comment by ivandack** [comment]
I have the same problem. I tried to use the `wrapper` prop, but it only adds a wrapper between the outer span and the skeleton element.

**Comment by kishanbharda** [comment]
Have anyone found any solution I have also same problem. Width is not working in %.

**Comment by Motii1** [comment]
Maybe it is not the best solution, but I started to wrap everything in `span` like this:
 ```
<span style={{width: '30%'}}>
    <Skeleton />
</span>
```
and it worked for me.

**Comment by Whooolia** [comment]
this should work as below

```     
<div style={{ width: '100%' }}>
      <Skeleton
             width="100%"
             height={calculateHeight()}
             style={{ backgroundColor: theme.color.grey }}
      />
</div>
```

**Comment by roiassa94** [comment]
Anyone got a solution?
@Whooolia solution was great, but it was not what the OP referred to.

When under a parent div with Flex or Grid, the skeleton in % does not appear.

Has anyone got a solution yet?

**Comment by rlaunch** [comment]
Having same issue also

**Comment by drews256** [comment]
Having this same issue.

**Comment by albertdugba** [comment]
Have the same issue

**Comment by srmagura** [comment]
This is solved in v3 via `containerClassName`. Thanks @rlaunch for the PR! 

I will also be adding a note to the README about this.
