### ISSUE TITLE
Skeleton is not showing in production

### ISSUE THREAD

**Issue by chidimo** [dvtng/react-loading-skeleton#79]
Hi. I find that all of a sudden I don't see any skeletons in production. It all works fine on my local. Anyone else experienced such a thing?

**Comment by morashko** [comment]
The same problem.

**Comment by efriandika** [comment]
Any information about this? I got the same problem too, 
It is disappeared in production mode

**Comment by efriandika** [comment]
When I checked by using inspect element, In dev mode I can find the css:
```
.css-1vmnjpn-skeletonStyles-Skeleton {
    ...
    ...
}
```

But in when my react app is in production mode, I cand find that css style. So that's why it is not showing et all.

**Comment by chidimo** [comment]
> When I checked by using inspect element, In dev mode I can find the css:
> 
> ```
> .css-1vmnjpn-skeletonStyles-Skeleton {
>     ...
>     ...
> }
> ```
> 
> But in when my react app is in production mode, I cand find that css style. So that's why it is not showing et all.
> 
> After investigating in last few hours, I find that this problem happen if we use `https://github.com/JedWatson/react-select` in the sampe page with this library.

I noticed same thing but I wasn't sure. This validates my observation.

**Comment by srmagura** [comment]
Should be fixed as a result of removing Emotion.
