### ISSUE TITLE
Skeleton does not work properly if we also use another library that is using @emotion/**

### ISSUE THREAD

**Issue by efriandika** [dvtng/react-loading-skeleton#82]
I find that, this does not work as expected if we use the other library that is using `@emotion/**` too.
In production mode, Skeleton will be dissapeared because there is no css style is generated.

I tried by using:
* React 17+ (Next.js 10)
* `https://github.com/JedWatson/react-select` version: latest
* `https://github.com/dvtng/react-loading-skeleton` version: latest

It used to work perfectly when I use `react-select` version 3 (it uses @emotion/** version 10)

**Comment by oesukam** [comment]
Facing the issue while using `https://github.com/dvtng/react-loading-skeleton` and `https://github.com/system-ui/theme-ui` as `theme-ui` also uses a different version of `@emotion/`

**Comment by srmagura** [comment]
Closing in favor of #80.
