### ISSUE TITLE
Circulair option

### ISSUE THREAD

**Issue by rickerd** [dvtng/react-loading-skeleton#9]
Loving this library.
It's easy and working like a charm.

But i'm missing shapes or images that could be occur in a skeleton.
![1_5goezexrmdfe71z8yz01fa](https://user-images.githubusercontent.com/1032429/41658624-4206a076-7497-11e8-97ce-3412365a064e.gif)

**Comment by patcon** [comment]
I think this can be closed, given #13 is merged in :)

**Comment by dvtng** [comment]
Agree!
