### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by clinton-mwachia** [dvtng/react-loading-skeleton#94]
Hello,
Is there documentation for this package? If there is, please provide the link.

**Comment by girishboke** [comment]
Hi @clinton-mwachia  I found simple example for this library, you can refer the link below.
[https://www.smashingmagazine.com/2020/04/skeleton-screens-react/](url)

seems you are looking for,
`npm install react-loading-skeleton`

**Comment by srmagura** [comment]
The project's README is the main documentation but that Smashing Magazine article is nice too, thanks for posting.
